#!/usr/bin/env python3
"""Generate the landing page's JS constants from the Python skills.

The landing page (deploy/agent/static/index.html) renders a live turnover-tax
and VAT comparison in the browser, before any network call. To do that it needs
the same constants the skills use. Two copies of a tax threshold is exactly the
failure mode the whole project exists to argue against - so the JS copy is
generated from the Python one, and CI asserts they still match.

The generated block is fenced in the HTML by:

    /* MIA:GENERATED-CONSTANTS:START ... */
    ...
    /* MIA:GENERATED-CONSTANTS:END */

Everything outside those sentinels is hand-written and never touched here.

Usage:
    python scripts/gen_web_constants.py            # rewrite the block in place
    python scripts/gen_web_constants.py --check    # exit 1 if it is out of date

--check is what CI runs. It never writes.
"""

from __future__ import annotations

import argparse
import importlib.util
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
SKILLS_DIR = REPO_ROOT / "skills"
PAGE = REPO_ROOT / "deploy" / "agent" / "static" / "index.html"

START = "/* MIA:GENERATED-CONSTANTS:START"
END = "/* MIA:GENERATED-CONSTANTS:END */"

TURNOVER_SKILL = "calculate-turnover-tax-south-africa"
VAT_SKILL = "check-vat-registration-south-africa"


def load_skill(directory: str) -> Any:
    """Import skills/<directory>/server.py in-process, by path.

    Same trick the gateway uses: deploy/ and skills/ are not packages, and each
    skill's module is called `server`, so they must be loaded under unique names.
    """
    path = SKILLS_DIR / directory / "server.py"
    if not path.exists():
        raise SystemExit(f"cannot find {path}")
    spec = importlib.util.spec_from_file_location(f"mia_gen_{directory.replace('-', '_')}", path)
    if spec is None or spec.loader is None:  # pragma: no cover - defensive
        raise SystemExit(f"cannot load {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def js_number(value: float) -> str:
    """Render a Python number the way a human would write it in JS.

    Rates stay as written (0.01); money and thresholds lose the float tail so
    the generated file reads like source, not like a serialisation artifact.
    """
    if value == int(value):
        return str(int(value))
    return repr(value)


def js_table(table: list[tuple[float, float, float]]) -> str:
    rows = ",".join("[" + ",".join(js_number(x) for x in row) + "]" for row in table)
    return "[" + rows + "]"


def build_block() -> str:
    """The full text between (and including) the sentinels."""
    turnover = load_skill(TURNOVER_SKILL)
    vat = load_skill(VAT_SKILL)

    tables = turnover.TURNOVER_TAX_TABLES
    limits = turnover.QUALIFYING_TURNOVER_LIMIT

    for year in (2027, 2026):
        if year not in tables:
            raise SystemExit(f"{TURNOVER_SKILL} has no {year} turnover-tax table")
        if year not in limits:
            raise SystemExit(f"{TURNOVER_SKILL} has no {year} qualifying limit")

    lines = [
        f"{START} - do not hand-edit between these sentinels.",
        "   Generated by scripts/gen_web_constants.py from the Python skills:",
        f"     skills/{TURNOVER_SKILL}/server.py",
        f"     skills/{VAT_SKILL}/server.py",
        "   CI runs `python scripts/gen_web_constants.py --check` and fails if these",
        "   drift. To change a number, change it in the skill and regenerate.",
        "   When this page is served by deploy/agent it prefers the live /api/position",
        "   endpoint; these are the offline fallback and the no-JS render. */",
        f"const T2027 = {js_table(tables[2027])};",
        f"const T2026 = {js_table(tables[2026])};",
        f"const LIMIT_NOW = {js_number(limits[2027])}, LIMIT_OLD = {js_number(limits[2026])};",
        f"const VAT_NOW = {js_number(vat.MANDATORY_REGISTRATION_THRESHOLD_ZAR)}, "
        f"VAT_VOL_NOW = {js_number(vat.VOLUNTARY_REGISTRATION_MINIMUM_ZAR)};",
        f"const VAT_OLD = {js_number(vat.PREVIOUS_MANDATORY_THRESHOLD_ZAR)}, "
        f"VAT_VOL_OLD = {js_number(vat.PREVIOUS_VOLUNTARY_MINIMUM_ZAR)};",
        f"const VAT_DEADLINE_DAYS = {js_number(vat.REGISTRATION_DEADLINE_BUSINESS_DAYS)};",
        END,
    ]
    return "\n".join(lines)


def splice(html: str, block: str) -> str:
    """Replace the fenced region, leaving every other byte untouched."""
    start = html.find(START)
    if start == -1:
        raise SystemExit(f"{PAGE} has no {START} sentinel")
    end = html.find(END, start)
    if end == -1:
        raise SystemExit(f"{PAGE} has no {END} sentinel after the start sentinel")
    return html[:start] + block + html[end + len(END) :]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit 1 if the page is out of date with the Python",
    )
    args = parser.parse_args()

    if not PAGE.exists():
        raise SystemExit(f"cannot find {PAGE}")

    current = PAGE.read_text(encoding="utf-8")
    updated = splice(current, build_block())

    if current == updated:
        print(f"up to date: {PAGE.relative_to(REPO_ROOT)}")
        return 0

    if args.check:
        print(
            f"OUT OF DATE: {PAGE.relative_to(REPO_ROOT)} does not match the Python skills.\n"
            "The page's constants have drifted from their source of truth.\n"
            "Run:  python scripts/gen_web_constants.py",
            file=sys.stderr,
        )
        return 1

    PAGE.write_text(updated, encoding="utf-8")
    print(f"regenerated: {PAGE.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
